export const AUTH = {
    SEND_OTP: 'SEND_OTP',
    GET_OTP: 'GET_OTP',
    VERIFY_OTP: 'VERIFY_OTP',
    RESEND_OTP: 'RESEND_OTP',
    USER_INFO: 'USER_INFO',
    FCM_TOKEN: 'FCM_TOKEN',
};


export const RESTAURANT = {
    GET_ALL_RESTAURANTS: 'GET_ALL_RESTAURANTS',
    GET_RESTAURANT_BY_ID: 'GET_RESTAURANT_BY_ID',
};

